theme: jekyll-theme-so-simple

title: "Gérard Rozsavolgyi Github Page"
tagline: "Page de présentation - cours en ligne"
description: "Page de présentation"
baseurl: ""
url: "https://roza.github.io"
lang: fr-FR
timezone: Europe/Paris

author:
  name: "Gérard Rozsavolgyi"
  email: example@domain.com
  links:
    - title: GitHub
      url: https://github.com/roza
      icon: fab fa-github

read_time: true
words_per_minute: 200
toc: true

comments: false

# Navigation
navigation_pages:
  - about.md
  - categories.md
  - publications.md

paginate: 10
paginate_path: /page:num/

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - Gemfile.ori
